export const countryOptions = [
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "UK", name: "United Kingdom", flag: "🇬🇧" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "MA", name: "Morocco", flag: "🇲🇦" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "HR", name: "Croatia", flag: "🇭🇷" },
];
